[project]
name = "06-build-compose-and-decorate-a-complete-traditional-oop-practice-series"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = []
